version: '3'

services:
   nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    db:
    image: "mongodb:latest"
    container_name: "mongodb" 
    restart: unless-stopped
    env_file: .env
    environment:
      - MONGO_URI
      - PORT
    ports:
      - "80:8080"
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    networks:
      - app-network
    command:  -- /home/node/app/node_modules/.bin/nodemon app.js